[package]
name = "nitrogen_helium"
version = "0.1.0"
authors = ["Aibhstin <aibhsec@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
data-encoding = "2.3.2"
ring = "0.16.20"
